aliases:
  - &install-tools
    name: Install tools
    command: |
      sudo npm install -g npm@latest
      sudo apt-get install rsync -y

  - &restore-npm-cache
    key: dependency-cache-{{ checksum "package.json" }}

  - &save-npm-cache
    key: dependency-cache-{{ checksum "package.json" }}
    paths:
      - node_modules

  - &npm-install
    name: Install packages
    command: npm install

defaults: &defaults
  working_directory: /tmp/web
  docker:
    - image: circleci/node:8-stretch

version: 2

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: *install-tools
      - restore-cache: *restore-npm-cache
      - run: *npm-install
      - save-cache: *save-npm-cache      
      - persist_to_workspace:
          root: /tmp/web
          paths:
            - .
  build_and_release:
    <<: *defaults
    steps:
      - checkout
      - run: *install-tools
      - attach_workspace:
          at: /tmp/web
      - run:
          name: Build frontend
          command: npm run build
      - add_ssh_keys:
          fingerprints:
            - "24:53:42:a2:fe:23:bb:ff:a8:25:80:fc:84:53:01:e4"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run:
          name: Upload release to dev
          command: rsync -avce ssh ./ $DEPLOYMENT_USER@$IP:$DEPLOYMENT_PATH
      - persist_to_workspace:
          root: /tmp/web
          paths:
            - .

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - build_and_release:
          context: dev
          requires:
            - install
          filters:
            branches:
              only: development